version: '3'
services:
  serviceregistry:
    image: gowthamvarma12/serviceregistry:0.0.1
    container_name: serviceregistry
    ports:
      - '8761:8761'
    healthcheck:
      test: ["CMD","curl","-f","http://serviceregistry:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
  configserver:
    image: gowthamvarma12/configserver:0.0.1
    container_name: configserver
    ports:
      - '9296:9296'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
    healthcheck:
      test: ["CMD","curl","-f","http://configserver:9296/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      serviceregistry:
        condition: service_healthy
  cloudgateway:
    image: gowthamvarma12/cloudgateway:latest
    container_name: cloudgateway
    ports:
      - '9090:9090'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
      - CONFIG_SERVER_URL=configserver 
    depends_on:
      configserver:
        condition: service_healthy
    